# Generated by Django 5.2.2 on 2025-06-10 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dbp_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dbp_max_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dbp_applicable_days', models.CharField(help_text='Comma-separated days (e.g. MON,TUE,WED)', max_length=50)),
                ('dap_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tmf_under_1h', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tmf_1h_to_2h', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tmf_after_2h', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wc_free_minutes', models.PositiveIntegerField(default=3)),
                ('wc_amount_per_block', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wc_block_duration', models.PositiveIntegerField(default=3, help_text='Minutes per block')),
            ],
        ),
        migrations.CreateModel(
            name='PricingConfigLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changes', models.TextField()),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pricingconfig')),
            ],
        ),
    ]
